#' Initialize an R package project
#'
#' Scaffolds a standard R package layout with a DESCRIPTION, namespace, test
#' suite, pkgdown config, R CMD check workflow, Air formatter config, and agent
#' guidance files.
#'
#' @param path Path where the package is created. The package name is taken from
#'   the final path component.
#' @param title One-line title for the DESCRIPTION.
#' @param confirm Logical. If TRUE, prompts for confirmation before creating the
#'   project (interactive sessions only).
#'
#' @return Invisibly, the `path` the project was created in.
#' @export
#'
#' @examples
#' init_package(path = file.path(tempdir(), "mypkg"), confirm = FALSE)
init_package <- function(path = getwd(), title = "What the Package Does",
                         confirm = TRUE) {
  cat("Your current working directory will be:\n")
  cat(path)

  if (confirm && interactive()) {
    user_input <- tolower(
      readline(
        prompt = "Do you wish to create an R package here? (y/yes to confirm): "
      )
    )
  } else {
    user_input <- "y"
  }

  if (!user_input %in% c("y", "yes")) {
    cat("Project initialization canceled.\n")
    return(invisible(path))
  }

  pkg <- basename(sub("[/\\\\]+$", "", path))

  dirs <- c(
    "R",
    "man",
    "tests/testthat",
    ".github/workflows"
  )
  for (d in dirs) {
    dir.create(file.path(path, d), recursive = TRUE, showWarnings = FALSE)
  }

  write_file <- function(rel, lines) {
    con <- file(file.path(path, rel))
    writeLines(lines, con)
    close(con)
  }

  write_file(
    "DESCRIPTION",
    c(
      paste0("Package: ", pkg),
      paste0("Title: ", title),
      "Version: 0.0.1",
      "Authors@R:",
      "    person(\"First\", \"Last\", , \"first.last@example.com\",",
      "           role = c(\"aut\", \"cre\"))",
      paste0(
        "Description: A short paragraph describing what ", pkg, " does."
      ),
      "License: MIT + file LICENSE",
      "Encoding: UTF-8",
      "Roxygen: list(markdown = TRUE)",
      "Suggests:",
      "    testthat (>= 3.0.0)",
      "Config/testthat/edition: 3"
    )
  )

  write_file("NAMESPACE", "# Generated by roxygen2: do not edit by hand")

  write_file("LICENSE", c("YEAR: 2026", "COPYRIGHT HOLDER: Your Name"))

  write_file(
    "LICENSE.md",
    c(
      paste0("# MIT License"),
      "",
      "Copyright (c) 2026 Your Name",
      "",
      "Permission is hereby granted, free of charge, to any person obtaining",
      "a copy of this software and associated documentation files (the",
      "\"Software\"), to deal in the Software without restriction, including",
      "without limitation the rights to use, copy, modify, merge, publish,",
      "distribute, sublicense, and/or sell copies of the Software, and to",
      "permit persons to whom the Software is furnished to do so, subject to",
      "the following conditions:",
      "",
      "The above copyright notice and this permission notice shall be",
      "included in all copies or substantial portions of the Software.",
      "",
      "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,",
      "EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF",
      "MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND",
      "NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS",
      "BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN",
      "ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN",
      "CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE",
      "SOFTWARE."
    )
  )

  write_file(
    ".Rbuildignore",
    c(
      "^.*\\.Rproj$",
      "^\\.Rproj\\.user$",
      "^LICENSE\\.md$",
      "^_pkgdown\\.yml$",
      "^docs$",
      "^pkgdown$",
      "^\\.github$",
      "^air\\.toml$"
    )
  )

  write_file(
    ".gitignore",
    c(
      ".Rproj.user",
      ".Rhistory",
      ".RData",
      ".Ruserdata",
      "inst/doc",
      "docs"
    )
  )

  write_file(
    "README.md",
    c(
      paste0("# ", pkg),
      "",
      paste0(title, "."),
      "",
      "## Installation",
      "",
      "```r",
      paste0(
        "# install.packages(\"devtools\")"
      ),
      paste0(
        "devtools::install_github(\"YOUR_USER/", pkg, "\")"
      ),
      "```"
    )
  )

  write_file(
    paste0("R/", pkg, "-package.R"),
    c(
      paste0("#' @keywords internal"),
      paste0("\"_PACKAGE\"")
    )
  )

  write_file(
    "R/hello.R",
    c(
      "#' Say hello",
      "#'",
      "#' @param name A name to greet.",
      "#' @return A greeting string.",
      "#' @export",
      "#' @examples",
      "#' hello(\"world\")",
      "hello <- function(name = \"world\") {",
      "  paste0(\"Hello, \", name, \"!\")",
      "}"
    )
  )

  write_file(
    "tests/testthat.R",
    c(
      paste0("library(testthat)"),
      paste0("library(", pkg, ")"),
      "",
      paste0("test_check(\"", pkg, "\")")
    )
  )

  write_file(
    "tests/testthat/test-hello.R",
    c(
      "test_that(\"hello returns a greeting\", {",
      "  expect_equal(hello(\"world\"), \"Hello, world!\")",
      "})"
    )
  )

  write_file(
    "_pkgdown.yml",
    c(
      paste0("url: https://YOUR_USER.github.io/", pkg, "/"),
      "template:",
      "  bootstrap: 5"
    )
  )

  write_file(
    "air.toml",
    c(
      "[format]",
      "line-width = 80",
      "indent-width = 2",
      'indent-style = "space"'
    )
  )

  write_file(
    ".github/workflows/R-CMD-check.yaml",
    c(
      "on:",
      "  push:",
      "    branches: [main]",
      "  pull_request:",
      "    branches: [main]",
      "",
      "name: R-CMD-check",
      "",
      "permissions: read-all",
      "",
      "jobs:",
      "  R-CMD-check:",
      "    runs-on: ${{ matrix.config.os }}",
      "    strategy:",
      "      fail-fast: false",
      "      matrix:",
      "        config:",
      "          - {os: ubuntu-latest, r: 'release'}",
      "          - {os: windows-latest, r: 'release'}",
      "          - {os: macos-latest, r: 'release'}",
      "    env:",
      "      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}",
      "      R_KEEP_PKG_SOURCE: yes",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - uses: r-lib/actions/setup-pandoc@v2",
      "      - uses: r-lib/actions/setup-r@v2",
      "        with:",
      "          r-version: ${{ matrix.config.r }}",
      "          use-public-rspm: true",
      "      - uses: r-lib/actions/setup-r-dependencies@v2",
      "        with:",
      "          extra-packages: any::rcmdcheck",
      "          needs: check",
      "      - uses: r-lib/actions/check-r-package@v2",
      "        with:",
      "          upload-snapshots: true"
    )
  )

  write_agent_files(
    path,
    c(
      "# R package - agent guide",
      "",
      paste0("An R package scaffolded with peacock."),
      "",
      "## Build and check",
      "",
      "- `devtools::load_all()` loads the package for interactive use.",
      "- `devtools::document()` regenerates man pages and NAMESPACE.",
      "- `devtools::test()` runs the test suite.",
      "- `devtools::check()` runs R CMD check.",
      "",
      "## Layout",
      "",
      "- `R/` - package source; one function per file.",
      "- `man/` - roxygen2-generated docs (do not edit by hand).",
      "- `tests/testthat/` - unit tests.",
      "- `DESCRIPTION` - package metadata and dependencies.",
      "- `NAMESPACE` - exports and imports (generated by roxygen2)."
    )
  )

  cat("R package initialized.\n")
  invisible(path)
}
