on:
  push:
    branches: [main]
    paths: ["pkg-py/**", "shared/**", ".github/workflows/python.yaml"]
  pull_request:
    paths: ["pkg-py/**", "shared/**", ".github/workflows/python.yaml"]

name: python

permissions: read-all

defaults:
  run:
    working-directory: pkg-py

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv sync --dev
      - run: uv run ruff check .
      - run: uv run ruff format --check .
      - run: uv run pytest -v
